PIECE_KEY_BASE = 3
PIECE_KEY_NUMBER_DIGITS = 4
PIECE_HIGHEST_DIGIT = str(PIECE_KEY_BASE - 1)
MAX_PIECE_KEY = ''.join([PIECE_HIGHEST_DIGIT]*PIECE_KEY_NUMBER_DIGITS)
MAX_NUMBER_PIECE_KEYS = int(MAX_PIECE_KEY, base=PIECE_KEY_BASE) + 1